# Generated by Django 3.1.5 on 2021-01-08 17:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('new_mail_login', models.CharField(blank=True, max_length=256, null=True)),
                ('new_mail_pass', models.CharField(blank=True, max_length=256, null=True)),
                ('old_mail_login', models.CharField(blank=True, max_length=256, null=True)),
                ('old_mail_pass', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='CREATED', max_length=256)),
            ],
            options={
                'verbose_name': 'account',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.CharField(max_length=256)),
                ('used_times', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.CharField(max_length=16)),
                ('port', models.CharField(max_length=8)),
                ('type', models.CharField(choices=[('HTTP', 'http_https'), ('SOCKS', 'socks'), ('FTP', 'ftp')], default='HTTP', max_length=8)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='CREATED', max_length=256)),
            ],
            options={
                'verbose_name': 'proxy',
            },
        ),
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='CREATED', max_length=256)),
            ],
            options={
                'verbose_name': 'user_agent',
            },
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=256)),
                ('last_post_id', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('last_post_days', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to='api.account')),
            ],
            options={
                'verbose_name': 'influencer',
            },
        ),
        migrations.CreateModel(
            name='AccountStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('monitor_count', models.IntegerField(default=0)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='api.account')),
            ],
            options={
                'verbose_name': 'account_statistics',
            },
        ),
        migrations.CreateModel(
            name='AccountActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('LOGIN', 'login'), ('MONITOR', 'monitor'), ('COMMENT', 'comment')], max_length=8)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DEFAULT', 'default'), ('SUCCESS', 'success'), ('ERROR', 'error')], default='DEFAULT', max_length=256)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='api.account')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='api.comment')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='api.influencer')),
            ],
            options={
                'verbose_name': 'account_activity',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounts', to='api.proxy'),
        ),
        migrations.AddField(
            model_name='account',
            name='useragent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounts', to='api.useragent'),
        ),
    ]
