# Generated by Django 3.1.5 on 2021-01-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountactivity',
            options={'verbose_name': 'account activity', 'verbose_name_plural': 'account activities'},
        ),
        migrations.AlterModelOptions(
            name='accountstatistics',
            options={'verbose_name': 'account statistics', 'verbose_name_plural': 'account statistics'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='influencer',
            options={'verbose_name': 'influencer', 'verbose_name_plural': 'influencers'},
        ),
        migrations.AlterModelOptions(
            name='proxy',
            options={'verbose_name': 'proxy', 'verbose_name_plural': 'proxies'},
        ),
        migrations.AlterModelOptions(
            name='useragent',
            options={'verbose_name': 'user agent', 'verbose_name_plural': 'user agents'},
        ),
        migrations.AlterModelTable(
            name='account',
            table='api_account',
        ),
        migrations.AlterModelTable(
            name='accountactivity',
            table='api_account_activity',
        ),
        migrations.AlterModelTable(
            name='accountstatistics',
            table='api_account_statistics',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='api_comment',
        ),
        migrations.AlterModelTable(
            name='influencer',
            table='api_influencer',
        ),
        migrations.AlterModelTable(
            name='proxy',
            table='api_proxy',
        ),
        migrations.AlterModelTable(
            name='useragent',
            table='api_useragent',
        ),
    ]
