# Generated by Django 3.1.5 on 2021-01-10 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210110_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountactivity',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='api.account'),
        ),
        migrations.AlterField(
            model_name='accountactivity',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='api.comment'),
        ),
        migrations.AlterField(
            model_name='accountactivity',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='api.influencer'),
        ),
    ]
